### ISSUE TITLE
[Bug] some issues in bpedia_3.8_enrichment.owl [sf#68]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#13] opened 2015-02-04 13:10 UTC
**Reported by moahmedsherif on 2012-10-09 14:52 UTC**
I run Jena-eyeball to check the enriched ontology "dbpedia\_3.8\_enrichment.owl", but it generate some errors.
like undeclared datatype' URIs \(http://dbpedia.org/datatype/litre, http://dbpedia.org/datatype/metre ...\)
also badURI: "owlapi:ontology:ont1"
I attached the complete log file generated by eyeball.

**Comment by patrickwestphal** [comment] 2015-02-04 13:10
**Commented by moahmedsherif on 2012-10-09 14:52 UTC**
Log file generated by eyeball

**Comment by patrickwestphal** [comment] 2015-02-04 13:10
**Updated by moahmedsherif on 2012-10-09 14:54 UTC**
- **assigned_to**: nobody --> lorenz_b

**Comment by LorenzBuehmann** [comment] 2015-02-07 15:10
I tried to reproduce it with JENA Eyeball 2.3:

* owlapi:ontology:ont1 is probably a problem in the OWL API, I'll ask on their mailing list
* "class not declared" warnings are reported because a) -assume owl flag was not used; b) OWL 2 is not supported

I'll close this issue because it's not a real bug.

**Closed by LorenzBuehmann** 2015-02-07 15:10 UTC
Labels: bug
