### ISSUE TITLE
[Bug] Rest interface [sf#69]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#14] opened 2015-02-04 13:10 UTC
**Reported by wormsbee on 2012-11-06 10:18 UTC**
curl --data-urlencode conf@AristotlePosNeg.conf "http://localhost:9099/interfaces/rest"

\{"learningresult":\{"error":"An error occured: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alg': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'learningProblem' of bean class \[org.dllearner.algorithms.ocel.OCEL\]: Bean property 'learningProblem' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?","stacktrace":org.springframework.beans.NotWritablePropertyException: Invalid property 'learningProblem' of bean class \[org.dllearner.algorithms.ocel.OCEL\]: Bean property 'learningProblem' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?,"success":"0"\}\}

**Comment by patrickwestphal** [comment] 2015-02-04 13:10
**Commented by wormsbee on 2012-11-06 10:19 UTC**

**Comment by LorenzBuehmann** [comment] 2015-02-10 15:35
I cannot reproduce this issue. Just from the stacktrace this could/should never happen because the setter setLearningProblem indeed exists in the super class AbstractCELA, thus I'll close this issue.

**Closed by LorenzBuehmann** 2015-02-10 15:35 UTC
Labels: bug
